### ISSUE TITLE
Error en "Nuevo calendario" (dre)

### ISSUE THREAD

**Issue by Jordi59** [olvidio/orbix#11]
dre -> Nuevo calendario -> Nuevo planing: con cualquier opción (p.ej., casas comunes, todo el año (2024)) da el siguiente error:
Fatal error: Uncaught Error: The script tried to call a method on an incomplete object. Please ensure that the class definition "web\DateTimeLocal" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition in /var/www/orbix/apps/web/Planning.php:102 Stack trace: #0 /var/www/orbix/apps/actividades/controller/calendario_ajax.php(74): web\Planning->dibujar() #1 {main} thrown in /var/www/orbix/apps/web/Planning.php on line 102

**Comment by olvidio** [comment]
cosas deprecadas por php 8.2
