### ISSUE TITLE
Cartas de presentación (error)

### ISSUE THREAD

**Issue by Jordi59** [olvidio/orbix#13]
Ha dejado de funcionar -> scdl -> direcciones -> cartas de presentación -> modificar.
(sirve para modificar los datos de las cartas de presentación)
Se escoge la dl y un población.
Ahora siempre saca una lista vacía. Debía sacar el listado de centros en esa ciudad.
No sé si puede tener que ver con algún filtro para no poder modificar regiones (porque el resultado que presenta es el mismo)

**Comment by olvidio** [comment]
No es error.
El problema es que se había guardado en la configuración del slickgrid que  NO mostrara ninguna columna.
