### ISSUE TITLE
Fallo en direcciones de centros

### ISSUE THREAD

**Issue by Jordi59** [olvidio/orbix#18]
En scdl -> direcciones -> cartas de presentación -> lista dl: se hace un lío con las direcciones de Mont-roig. El proceso ha sido: añadir una segunda dirección  (sede del club: Sant Antoni Maria Claret, 26); dejar ésta como principal y desmarcar la anterior (Sant Antoni Maria Claret, 27) que deja de ser principal. Seguía sancando la anterior dirección como primera en el listado (la del número 27). He quitado esta dirección que dejaba de ser principal. El caso es que ha seguido sacando en el listado la que había dejado de ser principal (la de número 27)  y no saca la nueva (que sí que es principal: la de número 26).
Conclusión: me parece que al hacer los listados se hace un lío con la que es principal y la que no (no sé si puede tener que ver también con lo de "propia": he hecho pruebas de quitar o poner, pero sigue fallando).

**Comment by olvidio** [comment]
El tema de las cartas de presentación no se actualiza automáticamente. Hay
que modificarlo individualmente.
Con el tema de directores porque no se tiene acceso a los cargos.
Con el tema direcciones, porque no está claro que criterio seguir.

Hay que ir a modificar la carta de presentación y se puede tener una por
cada dirección. Hay que anular una y poner la otra.

Missatge de Jordi Pérez ***@***.***> del dia dv., 29 de set.
2023 a les 11:13:
