### ISSUE TITLE
datos académicos profesores stgr

### ISSUE THREAD

**Issue by etchegaray** [olvidio/orbix#22]
En la BDU hemos recibido una sugerencia diciendo que los datos de profesores se pueden modificar tanto desde la BDU como desde Aquinate y esto ha causado o puede causar incoherencia en los datos. 

Ignoro si es posible extraer esos datos académicos de la BDU los "puede ver" Aquinate. Si fuera así, quizá sería conveniente impedir modificarlos en Aquinate y que los coja desde la BDU.

**Comment by olvidio** [comment]
pasado a discussion
