### ISSUE TITLE
Error en tabla alumnos-asignaturas

### ISSUE THREAD

**Issue by etchegaray** [olvidio/orbix#23]
Desde dln dicen que algunos alumnos no coincide lo que tienen en su tessera con lo que aparece en la tabla alumnos-asignatura. Me ha pasado tres nombres y efectivamente es así. No encuentro ninguna razón... Adjunto imagen de Ignacio Torrente  en la tabla y de su tessera...Como puede verse aparece que tiene pendientes Filosofía de la Naturaleza I y II y Metafísica I y II (entre otras muchas) y en cambio en su tessera aparecen como aprobadas... 

Otros dos con el mismo problema son José Antonio Delgado y Javier González Feria... los tres de dln

![image](https://github.com/olvidio/orbix/assets/15702387/10f6e9c3-52af-4cb9-8b1f-5ccee38fb281)

![image](https://github.com/olvidio/orbix/assets/15702387/88168764-9ba8-4560-9d73-cae8c3ec273d)

**Comment by olvidio** [comment]
Esto pasa cuando las notas no están guardadas en la dl correspondiente.
Para comprobar si hay más casos, hay que ir a Actas > resumenes > comprobar los datos del fichero notas 
Sucede cuando no se ha hecho el traslado.
